#!python3

from exploits.AdminBypass.main import link, run
import argparse

parser = argparse.ArgumentParser(
        description="Bypass windows administrator password requirement popup"
    )

subparsers = parser.add_subparsers(
    title="Comandos",
    description="Comandos disponibles",
    dest="command",
    required=True
)

# Subcomando: link
link_parser = subparsers.add_parser("link", help="link the executable file")
link_parser.add_argument("input_link", type=str, help="executable")
link_parser.add_argument("output_link", type=str, help="link tag name")

# Subcomando: run
run_parser = subparsers.add_parser("run", help="run a link")
run_parser.add_argument("input_run", type=str, help="linked tag")

args = parser.parse_args()

# Ejecutar comandos
if args.command == "link":
    link(args.input_link, args.output_link, 1)
elif args.command == "run":
    run(args.input_run)